// =============================================================================
// VISA Commercial Spend Analytics — DAX Starter Measures
// =============================================================================
// Table: Fact_CommercialSpend
// Storage mode: Direct Lake
// Last updated: 2026-07-21
//
// Usage: Import into the VISA Commercial Spend Analytics semantic model
//        via Tabular Editor, XMLA endpoint, or Power BI Desktop.
// =============================================================================

// -- Core spend metrics -------------------------------------------------------

Total Spend USD =
    SUM(Fact_CommercialSpend[SpendAmountUSD])

Transaction Count =
    SUM(Fact_CommercialSpend[TransactionCount])

Average Ticket USD =
    DIVIDE([Total Spend USD], [Transaction Count])

Interchange Revenue USD =
    SUM(Fact_CommercialSpend[InterchangeRevenueUSD])

// -- Risk / fraud metrics -----------------------------------------------------

Fraud Exposure Score =
    AVERAGE(Fact_CommercialSpend[FraudScore])

High Fraud Transactions =
    CALCULATE(
        [Transaction Count],
        Fact_CommercialSpend[FraudScore] >= 70
    )

// -- Approval metrics ---------------------------------------------------------

Approval Rate =
    DIVIDE(
        CALCULATE([Transaction Count], Dim_ApprovalStatus[ApprovalStatus] = "Approved"),
        [Transaction Count]
    )

Decline Rate =
    DIVIDE(
        CALCULATE([Transaction Count], Dim_ApprovalStatus[ApprovalStatus] = "Declined"),
        [Transaction Count]
    )

// -- Time intelligence --------------------------------------------------------
// NOTE: DATEADD/SAMEPERIODLASTYEAR return BLANK when filter context arrives via
// a non-date column of Dim_Date (e.g. Year) — this is NOT fixed by marking
// Dim_Date as a Date Table (dataCategory: Time); confirmed empirically via XMLA
// against the live model — see docs/design_notes.md Section 18. The fix below
// bypasses time-intelligence functions entirely using explicit Year-arithmetic
// filtering, which is self-scoping in every context (unfiltered, Year-filtered,
// or Date-filtered) and works correctly for both headline KPI cards (no filter)
// and the per-year trend table (grouped by Year).

Spend YoY % =
    VAR CurYear = MAX(Dim_Date[Year])
    VAR CurSpend = CALCULATE([Total Spend USD], FILTER(ALL(Dim_Date), Dim_Date[Year] = CurYear))
    VAR PriorSpend = CALCULATE([Total Spend USD], FILTER(ALL(Dim_Date), Dim_Date[Year] = CurYear - 1))
    RETURN
        DIVIDE(CurSpend - PriorSpend, PriorSpend)
