// =============================================================================
// VISA Commercial Spend Analytics — DAX Starter Measures
// =============================================================================
// Table: Fact_CommercialSpend
// Storage mode: Direct Lake
// Last updated: 2026-07-21
//
// Usage: Import into the VISA Commercial Spend Analytics semantic model
//        via Tabular Editor, XMLA endpoint, or Power BI Desktop.
// =============================================================================

// -- Core spend metrics -------------------------------------------------------

Total Spend USD =
    SUM(Fact_CommercialSpend[SpendAmountUSD])

Transaction Count =
    SUM(Fact_CommercialSpend[TransactionCount])

Average Ticket USD =
    DIVIDE([Total Spend USD], [Transaction Count])

Interchange Revenue USD =
    SUM(Fact_CommercialSpend[InterchangeRevenueUSD])

// -- Risk / fraud metrics -----------------------------------------------------

Fraud Exposure Score =
    AVERAGE(Fact_CommercialSpend[FraudScore])

High Fraud Transactions =
    CALCULATE(
        [Transaction Count],
        Fact_CommercialSpend[FraudScore] >= 70
    )

// -- Approval metrics ---------------------------------------------------------

Approval Rate =
    DIVIDE(
        CALCULATE([Transaction Count], Dim_ApprovalStatus[ApprovalStatus] = "Approved"),
        [Transaction Count]
    )

Decline Rate =
    DIVIDE(
        CALCULATE([Transaction Count], Dim_ApprovalStatus[ApprovalStatus] = "Declined"),
        [Transaction Count]
    )

// -- Time intelligence --------------------------------------------------------
// NOTE: Dim_Date must be marked as an official Date Table (dataCategory: Time)
// for DATEADD/SAMEPERIODLASTYEAR to resolve correctly whenever filter context
// arrives via a non-date column of that table (e.g. Year) — see
// docs/design_notes.md Section 18.

Spend YoY % =
    DIVIDE(
        [Total Spend USD]
            - CALCULATE([Total Spend USD], DATEADD(Dim_Date[Date], -1, YEAR)),
        CALCULATE([Total Spend USD], DATEADD(Dim_Date[Date], -1, YEAR))
    )

// Self-scoped to the most recent year in the model — use this (not the base
// measure) for headline KPI cards that have no year filter/slicer applied, so
// they always show a specific, defensible YoY figure instead of an unfiltered
// multi-year comparison.
Spend YoY % (Latest Year) =
    VAR LatestYear = CALCULATE(MAX(Dim_Date[Year]), ALL(Dim_Date))
    RETURN
        CALCULATE([Spend YoY %], Dim_Date[Year] = LatestYear)
